### ISSUE TITLE
Fails if installed to SD card on MK V

### ISSUE THREAD

**Issue by tylerjw** [sud0nick/PortalAuth#13]
https://github.com/sud0nick/PortalAuth/blob/070e1932e71040398d9ad4de591545d061450dd2/includes/scripts/PortalCloner.py#L34

This line is a hard link to where it installs if you select to install it to the internal disk.  It fails because of this if you have installed to the SD card.  There may be other hard links but a better thing to do would be to look in the only two places it could exist and set this base directory to the one that exists.

**Comment by sud0nick** [comment]
The directory /pineapple/modules/ has always contained symlinks to the actual location of the module which makes this the best choice for a base path rather than searching.  I'm closing this because it's not an actual issue.  Also, issues should be directed to the forums at https://forums.hak5.org/topic/37448-official-portal-auth/.

Edit: I also just realized you mentioned MK V in your title.  I no longer support the MK V version of the module and the current version hosted on here is only for Gen 6 Pineapples.
